/content/documents/visitscotland/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: e8d415ec-a08a-478c-bb98-2605a2854e47
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: en
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: c0e6cfc5-53fa-4a5f-89dd-9b23624d08a4
    hippo:name: Home Page
    hippo:versionHistory: aa7fef27-b30d-4832-adee-2bb8db95696e
    /content[1]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 0c486965-1409-46d2-a8e5-119bfc2eab62
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-10-05T10:55:44.150+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Top-Level
      visitscotland:title: Scotland, yours to enjoy. Responsibly.
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Let’s head back out and explore a little further with awe-inspiring landmarks and coastal seascapes for the perfect break.</p>

          <p>We’ll be exploring responsibly. Getting off the beaten track and away from busy spots, parking properly, closing gates and tidying up after ourselves.</p>

          <p>Once we’ve had our countryside fill, it’s time to enjoy one of our seven cultural cities, with their iconic attractions, relaxing accommodation choices, and innovative bars and restaurants.</p>

          <p>Then maybe a coastal seaside retreat with miles of sandy beaches during our extended <a href="https://www.visitscotland.com/about/themed-years/coasts-waters/" title="YOCW 2020">Scotland's Year of Coasts &amp; Waters</a>?</p>

          <p>After all, we deserve some quality time to ourselves, and with our friends and family.</p>
    /content[2]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: e51def55-8ed3-4eae-80df-1066a1eaff92
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-10-05T10:55:48.121+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Top-Level
      visitscotland:title: Scotland, yours to enjoy. Responsibly.
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Let’s head back out and explore a little further with awe-inspiring landmarks and coastal seascapes for the perfect break.</p>

          <p>We’ll be exploring responsibly. Getting off the beaten track and away from busy spots, parking properly, closing gates and tidying up after ourselves.</p>

          <p>Once we’ve had our countryside fill, it’s time to enjoy one of our seven cultural cities, with their iconic attractions, relaxing accommodation choices, and innovative bars and restaurants.</p>

          <p>Then maybe a coastal seaside retreat with miles of sandy beaches during our extended <a href="https://www.visitscotland.com/about/themed-years/coasts-waters/" title="YOCW 2020">Scotland's Year of Coasts &amp; Waters</a>?</p>

          <p>After all, we deserve some quality time to ourselves, and with our friends and family.</p>
    /content[3]:
      jcr:primaryType: visitscotland:General
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 3cc9b54e-5dc1-46bc-a1b0-f1c13bc14432
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-06-29T15:19:57.775+01:00
      hippostdpubwf:lastModificationDate: 2022-10-05T10:55:48.121+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2022-10-05T10:55:52.040+01:00
      hippotranslation:id: aa69f65e-dcae-46ea-b584-32fc6418ff21
      hippotranslation:locale: en
      visitscotland:breadcrumb: ''
      visitscotland:hideNewsletter: false
      visitscotland:newsletter: true
      visitscotland:seoDescription: Get all the information you need for your trip
        to Scotland! Book accommodation, discover new places to visit, find amazing
        things to do and more!
      visitscotland:seoNoIndex: false
      visitscotland:seoTitle: VisitScotland - Scotland's National Tourist Organisation
      visitscotland:teaser: Scotland. The country you love needs you. Travelling a
        little, can still make a big difference.
      visitscotland:theme: Top-Level
      visitscotland:title: Scotland, yours to enjoy. Responsibly.
      visitscotland:translation: ''
      /visitscotland:heroImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 6fe01b32-04e9-4d0f-86c9-b6b8bd246a67
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /visitscotland:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Let’s head back out and explore a little further with awe-inspiring landmarks and coastal seascapes for the perfect break.</p>

          <p>We’ll be exploring responsibly. Getting off the beaten track and away from busy spots, parking properly, closing gates and tidying up after ourselves.</p>

          <p>Once we’ve had our countryside fill, it’s time to enjoy one of our seven cultural cities, with their iconic attractions, relaxing accommodation choices, and innovative bars and restaurants.</p>

          <p>Then maybe a coastal seaside retreat with miles of sandy beaches during our extended <a href="https://www.visitscotland.com/about/themed-years/coasts-waters/" title="YOCW 2020">Scotland's Year of Coasts &amp; Waters</a>?</p>

          <p>After all, we deserve some quality time to ourselves, and with our friends and family.</p>
  /site-search-results:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 4175075d-f908-4b6d-ae0b-5b7951546907
    hippo:name: search-results
    hippostd:foldertype: [new-translated-folder, new-page, new-module]
    hippotranslation:id: ff87714b-7240-4eab-b6bd-12b1ff545ee3
    hippotranslation:locale: en
    /content:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: acf1f6a2-cf2e-4fdb-b758-145748f65915
      hippo:name: Search results
      hippo:versionHistory: 65ad9310-5362-4ce7-b833-dd2f30f93601
      /content[1]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: da149723-d3b2-4b89-8900-9cd7c89fb278
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostd:transferable: false
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T13:37:34.580Z
        hippostdpubwf:lastModificationDate: 2022-03-10T13:52:25.904Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[2]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
        jcr:uuid: 4841a934-40d3-4a25-b310-29a41444def6
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T13:37:34.580Z
        hippostdpubwf:lastModificationDate: 2022-03-10T13:38:22.864Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
      /content[3]:
        jcr:primaryType: visitscotland:General
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 8aff8e26-0281-45e2-8b95-5a708cdb06ca
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2022-03-10T13:37:34.580Z
        hippostdpubwf:lastModificationDate: 2022-03-10T13:38:22.864Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2022-03-10T17:30:47.419Z
        hippotranslation:id: 389c358c-554d-4201-a9cc-56732e7e313b
        hippotranslation:locale: en
        visitscotland:breadcrumb: ''
        visitscotland:hideNewsletter: true
        visitscotland:seoDescription: Search results
        visitscotland:seoNoIndex: true
        visitscotland:seoTitle: Search results
        visitscotland:teaser: Search results
        visitscotland:theme: Simple
        visitscotland:title: Search Results
        visitscotland:translation: ''
        /visitscotland:heroImage:
          jcr:primaryType: hippogallerypicker:imagelink
          hippo:docbase: a5b5922e-d0d5-420c-af2d-670768cf7bd6
          hippo:facets: []
          hippo:modes: []
          hippo:values: []
        /visitscotland:introduction:
          jcr:primaryType: hippostd:html
          hippostd:content: <p>Search results</p>
